# Generated by Django 3.2.3 on 2021-09-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_homepost_userpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
