# Generated by Django 3.2.7 on 2021-09-26 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_userpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='author',
        ),
        migrations.AddField(
            model_name='userpost',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
